apiVersion: v1
kind: Pod
metadata:
  name: ${{ values.name }}
spec:
  containers:
  - name: app
    image: images.my-company.example/${{ values.name }}:v4
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "${{ values.memoryLimit }}"
        cpu: "${{ values.cpuLimit }}"
  - name: log-aggregator
    image: images.my-company.example/log-aggregator:v6
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"